# -*- coding: utf-8 -*-
"""Project1_FIN620

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dhkQvINa4rumNvgupPk1vY1Nkhz956LJ

<img src="https://www.viewfromthebridge.co.uk/wp-content/uploads/2021/03/ESG-300x249.png" width="500px" align="right">

---



# Asset Allocation Methods: ESG Integration 

Luc C. Smith 


---

## Summary & Methods:

---




Ethical topics have been growing throughout the industries of the world, and finance is one of them. With this, ethically responsible investing has been on the rise, but no set way has been given on how to do so. Here, different integrations of ethical investing are to be shown with popular methods of asset allocation (choosing where to place one's capital effectively). 5 different methods are attempted, using the famous Mean-Variance objective function, its alternatives, and even its extension as the Black-Litterman model. These traditional asset allocation models are to be combined with sample company ESG ratings, which aim to assess their ethical standards and practices given specific data.

## Environmental, Social, and Governance (ESG): Overview



---



The growing term to define and describe sustainable and ethical behaviors of companies has come to be known as ESG: Environmental, Social, and Governance. This provides a total overview of a company's ethical standards and practices through the examination of 3 major pillars as named. Each one pertains to a major ethical area in which companies affect through their practices. As known, many companies, if not all, pollute the environment through their operations, so the Environmental pillar aims to assess this area of a firm. Companies can also affect social areas such as people's lives, employees' treatment, and even social causes. Lastly, companies can participate in corruption related events, unethical governing practices, and more. ESG enables the ability to capture all of these areas of a firm to assess how ethically sound they are or how ethically bad they may be as a result of their practices and ideals. With this, investors can understand how specific industries and their companies are doing ethically. Furthermore, it can even be understood how they compare to its competitors and other companies. This can allow investors to customize their investment portfolios according to ethical standards and preferences. One may wish to only give money to companies that aim to stop pollution, for example. Also, one may desire to only invest in a company that helps social causes and strictly deviates from biased and corrupt politics. ESG allows this to happen more efficiently, so it may be possible to integrate this component in asset allocation to automate the wealth management process even further through expanding customization options. With these ideas, each pillar can be more closely examined:



* Environmental Pillar: This ESG pillar aims to assess a company's environmental effects and vision. Many pollute through their daily activities and even destroy nature. Some, however, participate in sustainable processes to avoid this, and others are even aiming to stray away from these paths of pollution. We are now seeing alternative fuels being used, alternative processes, and even alternative products such as electrical cars. The following are some factors that can help make up this ESG pillar: greenhouse gases emissions, amount of waste spilled, alternative energy being used, amount of energy being used, sustainable views, etc.

* Social Pillar: This ESG pillar aims to assess a firm's social effects. This includes a wide range of topics such as relationships with people, treatment of employees, work conditions, compensation, training and education, diversity, political stances, and even social causes. 

- Governance Pillar: This ESG pillar aims to assess a company's governance standards. These focus on how the company is managed from top levels of control. Here, topics such as corruptness, transparency, diversity, and bias are examined. Specifically, top floor executives are taken into account, for their standards, practices, and policies can be unfair or even misleading. As an example, a company may perform badly in this pillar if they have a small top level management group that hogs all of the resources and compensation for themselves.

## Asset Allocation: Overview


---


Asset allocation is critical for wealth management and investing activities. This is what decides how capital is allocated towards different assets for investing purposes. With this, there are many different methods of asset allocation since there are many different investing preferences, purposes, and goals. Some investors may seek greater risk and returns while others may seek greater diversification and minimum risk. With the ESG integration, some investors may be more interested in ethical practices than others, for some may simply want to seek the least amount of risk possible regardless of ESG integration. As a result, there are many ways to choose an effective asset allocation method in order to best fit a purpose and preference. The foundation of asset allocation can be seen through Markowitz Portfolio Theory, which provides a method to effectively choose an exact amount of capital to place in specific assets in order to minimize risk. With this, extensions ended up coming after in order to better fit investor preferences, such as the Black-Litterman model. This extension followed to allow investor views to be taken into account for asset allocation decisions, which was a flaw of Markowitz Portfolio Theory.

- Markowitz Portfolio Theory: the very basic form of this idea aims to minimize the risk of an investment portfolio, which is observed as volatility (standard deviation). However, its more sophisticated version minimizes risk given a level of return and with a certain risk-aversion parameter. Investors with higher risk-aversion seek to emphasize minimizing the risk while those with a lower one aims to maximize the return. This model is known as the Mean-Variance objective function, which is to be shown in the next section. 

- Black-Litterman: this model provides an extension to the Markowitz and Mean-Variance ideas by integrating the views of the investors even further. Here, specific asset views are taken into account in order to see which ones should receive more allocation in combination to minimizing the risk in the form of volatility.

## ESG Integration Methods:


---

With the two components discussed, they can now be combined to truly see how investors can use ESG specific information to allocate their capital in forms of investment decisions. Here, 5 different approaches are to be used as previously stated. They are the following:
1. ESG threshold constraint added to the Mean-Variance objective function:
  - Minimize(Volatility - A**returns* *weights) subject to ESG Rating => x 
  - A is the risk-aversion variable.
  - x is the portfolio ESG rating that must hold.

2. Regulator term addition to Mean-Variance function:
  - Minimize(Vol. - A* *returns** *weights + esg**weights) 
  - esg is the ESG score of the asset.

3. Alternative Mean-Variance Function:
  - Minimize(0.5* A* *Vol - esg* *weights)

4. Black-Litterman: ESG ratings as views:
  - this model takes in a vector of investor views of returns (Q), which is to be replaced by the ESG scores to fit this integration.

5. E, S, G separate pillar constraints with Mean-Variance Function:
  - Minimize(Volatility - A**returns* *weights) subject to E rating >= x, S rating >= y, G rating >= z
  - x is the Environmental pillar score.
  - y is the Social pillar score.
  - z is the Governance pillar score.

## Tools of Implementation: Python


---



Another idea being tied to the integration of ESG in asset allocation is automation. Many tools exist nowadays that enable tasks to be automated. Python has been one of the most popular tools for such things, especially in the financial and data world since it contains many open packages to be used for these areas. Even better, it is incredibly simple to use compared to others. Python has a great deal of efficiency for working with data and analytics, so its language and packages are to be used here. The following are the packages needed to implement the discussed methods:
- NumPy: mathematical and vectorized tools.
- Pandas: tabular analytics and manipulation.
- Matplotlib: visualization tools.
- yfinance: gathering stock price data.
- pandas_datareader: market cap. data needed for the Black-Litterman model.
- CVXPY: optimization tools.
- cov_nearest: statistical modelling adjustments for the Black-Litterman model.

# Implementation: 


---

- Before starting the processes, the named packages need to be imported first:
"""

#Necessary packages:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf             #Stock price data
import pandas_datareader as web   #Market cap data 
import cvxpy as cp                #Optimization 
from statsmodels.stats.correlation_tools import cov_nearest  #adjusting BL model

"""- With the necessary tools in place, the ESG scores can be gathered from a sample file for the members of the S&P Index:"""

#Get ESG scores:
scores_path = '/content/scores.csv'   
scores = pd.read_csv(scores_path)     #Read csv file
scores.head()                         #Show data portion of data

"""- With the ESG scores gathered for the companies, sample stocks can be chosen. First, the ticker names can be shortened just to their symbols for price data gathering in the next steps:"""

#Make stock symbols the index:
scores.index = scores.Ticker.str.split().str[0] 
scores.drop(scores.columns[0], axis=1, inplace=True)  #Drop Ticker column
scores.head()

"""- With the ESG scores ready to be used, the following sample stocks can be chosen for a simplified example. Yahoo Finance can be used to gather their price data with the yfinance package:"""

#Choosing stocks to exemplify:
stocks = ['AMZN','IBM','TSLA','AAL','UAL','DAL',
          'MRK','MRNA','PFE','GS','BAC','ECL','WFC','CVX',
          'BK', 'CDW', 'CTSH','MCO','NOC','AAPL','ABT','AEE',
          'FANG','ALK','ADI','AIZ','AKAM','AMD','AOS',
          'BA','AVY','CBRE','DHI','DVA']

#Narrowig down scores to above stocks only:
stock_scores = scores.loc[stocks]

#Getting closing stock price data: Yahoo Finance
data = yf.Tickers(stocks) 
port = data.history(period='1d', start='2019-01-01', end='2022-01-01').Close
port.head()

"""- The needed metrics of risk and return can now be calculated with the price data and added to the table next to the stocks and their ESG scores for organized readability of information. Returns are simply the average yearly percentage change of stock prices. The volatility is in form of yearly standard deviation (daily std. times the square root of 252 trading days in a year):"""

#Annual Returns + Cov Matrix:
year_ret = port.resample('Y').last().pct_change().mean()   #Average Yearly 
cov = port.pct_change().cov()

#Joining returns + volatility with ESG scores:
stock_scores['Returns'] = np.round(year_ret*100, 0)
stock_scores['Volatility'] = np.round(port.pct_change().std()*np.sqrt(252)*100, 2) 
stock_scores

"""
- With the information above, the best ethical companies can be seen overall and for each specific ESG pillar along with the return and risk metrics. With these, the optimization of the 5 methods named previously can begin to find the proper asset allocation for each company above given specific constraints. Before doing the optimization, one of the methods (the Black-Litterman approach) needs some steps before proceeding. It first needs market capitalization weights of the stocks, which can be calculated with the market capitalizations found in Yahoo Finance. The weights simply come out to be the individual market capitalizations of each stock divided by the total sum.
"""

#Get market cap weights:
import pandas_datareader as web           
mcs = web.get_quote_yahoo(stocks)['marketCap'].values  
mcs_w = mcs / mcs.sum() 
mcs_w

"""- Now, the necessary Black-Litterman variables can be defined. The risk-aversion (A) is needed, the covariance matrix (S), the implied equilibrium excess returns (pi), the views vector (Q), the link matrix (P), the scalar tau, c, and the uncertainty of views matrix (omega). All of these are calculated according to Meucci's formulas and findings as shown:"""

S = cov  #Cov matrix (S)
A = 1.2  #Risk-aversion (A)

#Implied Equilibrium Excess Returns (pi):
    #pi = 2A*S*w -> Meucci
pi = 2.0*A*np.dot(S, mcs_w)

#Views Vector (Q): ESG scores
Q = stock_scores.Total.values

#Link Matrix (P):
P = np.zeros((34,34))
np.fill_diagonal(P, 1)

#Scalar (tau), c, and Uncertainty of views matrix (omega):
    #tau = 1 / length of time series --> Meucci
    #c = 1 --> Meucci
    #omega = 1/c*P*S*P^T --> Meucci
tau = 1.0 / float(len(port))
c = 1.0
omega = np.dot(np.dot(P, S), P.T) / c

"""- Now, the Black-Litterman posterior returns and covariance matrix can be calculated using the variables defined above to produce the adjusted metrics of the stocks taking into account the ESG scores as the investor views. Again, the equations are according to Meucci and his findings:"""

## BL Excess Returns:
    # = pi + tau*S*P^T * (tau*P*S*P^T + omega)^-1 * (Q - P*pi)
post_pi = pi + np.dot(np.dot(tau*np.dot(S, P.T), 
          np.linalg.inv(tau*np.dot(np.dot(P, S), P.T) + omega)), 
          (Q - np.dot(P, pi)))

# BL Covariance Matrix:
    # = (1+tau)*S - tau^2*S*P.T * (tau*P*S*P.T + omega)^-1 * P*S
post_S = (1.0+tau)*S - np.dot(np.dot(tau**2.0*np.dot(S, P.T), 
        np.linalg.inv(np.dot(tau*np.dot(P, S), P.T) + omega)), np.dot(P, S))

symS = (post_S + post_S.T) / 2   #Make it symmetric
semidefS = cov_nearest(symS)     #Ensure strict positive semi-definite

semidefS    #Adjusted covariance matrix to calculate risk

"""- With the Black-Litterman metrics adjusted with the ESG scores as investor views, the optimization can occur for all methods. For this, a function can be constructed to save lines of code and non-necessary repetitions:"""

#Defining variables to be used as NumPy arrays for dot product operations:
ret = stock_scores.Returns.values  
esg = stock_scores.Total.values
e_esg = stock_scores.Environmental.values
s_esg = stock_scores.Social.values
g_esg = stock_scores.Governance.values

# Optimization Function:
def opt(fun=5):
  '''
  fun: 1 for first Mean-Variance objective function, 2 for regulator addition, 
       3 for alternate obj. function, 4 for Black-Lit. method, 5 for E,S,G separate
       pillars method.
  returns: array of optimal weights for given method.
  '''
  #Set Variables needed for optimization:
  w = cp.Variable(len(ret))             #List of weights
  rating = w@esg                        #ESG rating of portfolio
  e_rating = w@e_esg                    #Environmental rating
  s_rating = w@s_esg                    #Social rating
  g_rating = w@g_esg                    #Governance rating
  risk = cp.quad_form(w, cov)           #Volatility 

  #First Mean-Variance Objective Function Method:
  if fun == 1:
    obj = cp.Minimize(risk - A*ret@w)  #Mean-Variance Obj Func.
    cons = [cp.sum(w)==1, w>=0, w<=0.15, rating>=7.5]  #Constraints

  #ESG regulator addition to funct.: (Method 2)
  elif fun == 2:
    obj = cp.Minimize(risk - A*ret@w + esg@w) #Regulator = esg * weights
    cons = [cp.sum(w)==1, w>=0, w<=0.15]      #Constraints

  #Alternate obj. funct. + ESG regulator: (Method 3)
  elif fun == 3: 
    obj = cp.Minimize(0.5*A*risk - esg@w) 
    cons = [cp.sum(w)==1, w>=0, w<=0.15]  #Constraints

  #Black-Litterman (Method 4):
  elif fun == 4:
    risk_bl = cp.quad_form(w, semidefS)       #New Risk Term
    obj = cp.Minimize(risk_bl - A*post_pi@w)  #Obj. Funct. With BL returns
    cons = [cp.sum(w)==1, w>=0, w<=0.15]      #Constraints

  #E,S,G Separate pillar contraints (Method 5):
  else: 
    obj = cp.Minimize(risk - A*ret@w)                 #Mean-Variance Obj Func.
    cons = [cp.sum(w)==1, w>=0, w<=0.15,              #Constraints
            e_rating>=7, s_rating>=8, g_rating>=6.5]  

  #Solve optimization:
  prob = cp.Problem(obj, cons)
  prob.solve(solver=cp.ECOS)

  return w.value.round(3)  #Return array of optimal weights

"""- With the function designed, it can now be called for each method to see which one better integrates ESG into asset allocation. To do this, the function simply needs to be called for each method with the appropriate number 1-5:"""

#Methods optimized:
m_1, m_2, m_3, m_4, m_5 = opt(1), opt(2), opt(3), opt(4), opt()
m_1

"""- As seen above, the optimal weights for the methods are given from the function constructed. With this, they can each now be plotted for a clear view on how each method allocated capital to each asset while taking into account its specific constraints and models:"""

# Commented out IPython magic to ensure Python compatibility.
#Creating Plots of Optimal Weights:
# %matplotlib inline

#Defining subplots and variables of size, data, and labels:
f, axes = plt.subplots(5,1, figsize=(15,35))
x = np.arange(len(stocks))
methods = [m_1, m_2, m_3, m_4, m_5]
titles = ['ESG Score Constraint', 'ESG Regulator Added', 'Alternate Func. w/ Regulator',
          'Black-Litterman: ESG as Views', 'E,S,G Separate Constraints']

#Plotting bar charts for each method:
for i in range(5):
  axes[i].bar(x, methods[i])
  axes[i].set_xticks(x, stocks, rotation=45)
  axes[i].set_title(titles[i], fontsize=25)
  axes[i].set_ylabel('Allocation Weight', fontsize=15)

"""### Method 1: ESG Score Constraint Analysis:

- As seen above, the constraint placed upon the Mean-Variance objective function regarding total ESG scores seems to work well. It makes sense in the way the allocations are made since many high ESG rated stocks received noticeable allocation while some other regular ones still received some allocation as well such as Tesla. This method may be of good use with the right amount of stocks and constraints. Depending on the investor, their ESG constraint can be taken and implemented in this way to control the total ESG portfolio score, which will then represent either high ESG firms or low ones. This method may be too simple still, so other constraints may need to be added and explored. Also, it may prove useful to iterate through it with many different constraints and stocks to see how stable and consistent it remains.

### Method 2: ESG Regulator Addition Analysis:



- The second method, as seen, does not work well at all. All of the allocation is placed as if this regulator was not even added into the objective function. This makes sense as the ESG scores are on a scale of 10, and the returns and volatility of the stocks are much larger than that, so the returns end up taking all of the attention in this method. As seen, all stocks with high returns have the allocations while highly ESG rated firms have nothing at all. In order to proceed with this method, one would either need to adjust the scale of the ESG scores to better match the returns or even add a penalty/enhancer variable to the ESG regulator to mimic an investor's preference in this sense. For example, if someone is very ESG driven, this enhancer variable, 'Y' as an example, can be a number like 5 and multiplied by the ESG score, turning it into a more powerful regulator in the objective function. This could possibly be able to better translate ESG scores of this scale through this method.

### Method 3: Alternate Objective Function + ESG Regulator Analysis

- This method has the opposite result of method 2. As seen, all of the allocation automatically goes to the highest ESG rated stocks. No allocation is given to any other stock, so this ESG regulator overtakes the model. This is also an issue as some investors may not want to give all of their allocation to ESG firms only, so more additions to this function are necessary or even other constraints regarding returns.

### Method 4: Black-Litterman - ESG Scores as Views Analysis

- This method ended up having the same exact result as method number 3. It also allocated all towards highly ESG rated stocks. This makes sense since it took the ESG scores as the views, which favor higher ratings. Again, this isn't optimal as all allocation automatically goes towards high ESG rated stocks only based on this, and different investors may want different factors involved as well. Either more constraints need to be added or the approach needs to be different. The ESG scores could potentially come into play within the uncertainty variable, omega, instead as an example. This can be further studied and researched to possibly attain better results.

### Method 5: E, S, G Pillar Separated Constraints Analysis

- The last approach implemented here showed each of the ESG pillars with their own individual scores being considered through constraints. This approach seemed to work well as there was allocation towards quite a few different stocks. Some of them have great ESG scores and some not really, showing good differentiation. This is especially useful for investors seeking deeper customization as they can pick which ESG pillars are of more importance to their preferences. This can be further examined through iterations of different constraints in order to see how the results differ for different values, for there are many possible combinations here.

# Conclusion:


---


It is clear that ESG can be incorporated in asset allocation algorithms. Here, there have been quite a few approaches, with some proving to be promising and others lacking in some areas. However, there have been insights from them all with potential to make adjustments and explore new additions. The next steps are to iterate through the methods of constraints here and to explore the addition of an enhancer variable or even scaled ESG scores to better fit the regulator method. The Black-Litterman way also needs to be worked out with either adding constraints to the original model on ESG scores or even trying to use the uncertainty variable for them instead. In addition, more approaches will be researched to see what else can be done. They will then all be iterated through in order to see which are more stable and which make the most sense. A model that is able to provide great customization while not being too complex is desired.

# References:


---



1. Mean-Variance Optimization and the CAPM (Martin Haugh - 2016)


2. An Introduction to Modern Portfolio Theory: Markowitz, CAP-M, APT and Black-Litterman (Dr. Graeme West - 2004)


3. The Black-Litterman Approach: Original Model and Extensions (Attilio Meucci - 2010)


4. Optimal ESG Portfolios: an example for the Dow Jones Index (Anatoly Schmidt - 2020)
"""